"""Static catalog of ``MainWindow.open_module`` keys for widgets that need to
let the user pick a destination screen (e.g. the Launch Button widget).

Mirrors the ``module_key`` values wired up in ``main.py``'s menu actions, kept
here as a flat, human-labeled list rather than introspected at runtime so
widget code in ``ui/`` doesn't need to import the top-level ``main`` module.
"""

from __future__ import annotations

from typing import List, Tuple

MODULE_ACTIONS: dict[str, str] = {
    "menu.new_incident": "New Incident",
    "menu.open_incident": "Open Incident",
    "menu.save_incident": "Save Incident",
    "menu.settings": "Settings",
    "menu.notification_center": "Notification Center",
    "edit.aircraft": "Aircraft",
    "edit.canned_comm_entries": "Canned Communication Entries",
    "communications.217": "Communications Resources (ICS-217)",
    "edit.ems": "EMS Agencies",
    "edit.equipment": "Equipment",
    "edit.hazard_types": "Hazard Type Library",
    "edit.hospitals": "Hospitals",
    "edit.objectives": "Objectives",
    "edit.personnel": "Personnel",
    "edit.resource_types": "Resource Type Library",
    "edit.safety_templates": "Safety Analysis Templates",
    "edit.task_types": "Task Types",
    "edit.team_types": "Team Types",
    "edit.units_organizations": "Units and Organizations",
    "edit.vehicles": "Vehicles",
    "command.incident_dashboard": "Incident Command Dashboard",
    "command.unit_log": "Command Unit Log ICS-214",
    "command.chat": "Incident Chat",
    "command.incident_overview": "Incident Overview",
    "command.iap": "Incident Action Plan Builder",
    "command.objectives": "Incident Objectives (ICS-202)",
    "command.staff_org": "Incident Organization",
    "command.sitrep": "Situation Report (ICS-209)",
    "planning.glance": "Planning Dashboard",
    "planning.unit_log": "Planning Unit Log ICS-214",
    "planning.op_manager": "Operational Period Manager",
    "planning.demobilization": "Demobilization Planner",
    "planning.meetings": "Meeting Planner",
    "planning.sitrep": "Situation Report",
    "planning.tactics_planner": "Tactics and Resources Planner",
    "operations.dashboard": "Operations Dashboard",
    "operations.unit_log": "Operations Unit Log ICS-214",
    "operations.section_org": "Operations Section Organization",
    "operations.team_status": "Team Status Board",
    "operations.task_board": "Task Board",
    "operations.team_location_map": "Team Location Map",
    "logistics.dashboard": "Logistics Dashboard",
    "logistics.unit_log": "Logistics Unit Log ICS-214",
    "logistics.211": "Check-In ICS-211",
    "logistics.resource_status": "Resource Status Board",
    "logistics.213rr": "Resource Requests (ICS-213RR)",
    "logistics.facilities": "Facilities Manager",
    "comms.traffic_log": "Communications Dashboard",
    "comms.unit_log": "Communications Unit Log ICS-214",
    "comms.205": "Communications Plan ICS-205",
    "comms.log_board": "Communications Log (ICS-309)",
    "comms.log_entry": "Log & Entry",
    "comms.quick_entry": "Quick Entry",
    "comms.chat": "Chat Messaging",
    "comms.213": "ICS 213 Messages",
    "comms.notifications": "Notification Feed",
    "comms.notification_settings": "Notification Settings",
    "intel.dashboard": "Intel Dashboard",
    "intel.unit_log": "Intel Unit Log ICS-214",
    "intel.subjects": "Subjects",
    "intel.leads": "Leads",
    "intel.items": "Intel Items",
    "intel.assessments": "Assessments",
    "intel.log": "Intel Log",
    "intel.forms": "Forms",
    "medical.unit_log": "Medical Unit Log ICS-214",
    "medical.206": "Medical Plan ICS 206",
    "safety.unit_log": "Safety Unit Log ICS-214",
    "safety.208": "Safety Message ICS-208",
    "safety.215A": "Incident Safety Analysis ICS-215A",
    "safety.risk_manager": "Incident Hazard Register",
    "safety.iwi": "Safety Incident Reports (IWI)",
    "liaison.dashboard": "Liaison Dashboard",
    "liaison.unit_log": "Liaison Unit Log ICS-214",
    "liaison.agencies": "Agency Directory",
    "liaison.reporting": "Reporting Board",
    "liaison.customer": "Customer Requests & Feedback",
    "public.dashboard": "Public Information Dashboard",
    "public.unit_log": "Public Information Unit Log ICS-214",
    "public.media_releases": "Messages / Releases",
    "public.misinformation": "Rumor / Misinformation",
    "public.inquiries": "Media Log",
    "public.talking_points": "Talking Points",
    "public.templates": "Letterhead / Templates",
    "public.distribution": "Distribution Log",
    "finance.dashboard": "Finance/Admin Dashboard",
    "finance.unit_log": "Finance Unit Log ICS-214",
    "finance.time": "Time Tracking",
    "finance.procurement": "Expenses & Procurement",
    "finance.summary": "Cost Summary",
    "toolkit.projection_dashboard": "Projection Dashboard",
    "toolkit.sar.missing_person": "Missing Person Toolkit",
    "toolkit.sar.pod": "POD Calculator",
    "toolkit.disaster.damage": "Damage Assessment",
    "toolkit.disaster.urban_interview": "Urban Interview Log",
    "toolkit.disaster.photos": "Damage Photos",
    "planned.promotions": "External Messaging",
    "planned.vendors": "Vendors & Permits",
    "planned.tasking": "Quick Assignments",
    "planned.health_sanitation": "Health & Sanitation",
    "toolkit.initial.overview": "Initial Information",
    "toolkit.initial.hasty": "Early Tasking",
    "library": "Browse Library",
    "help.user_guide": "User Guide",
    "help.about": "About",
    "window.home_dashboard": "Home Dashboard",
}


def list_module_actions() -> List[Tuple[str, str]]:
    """Return ``(module_key, label)`` pairs sorted by label for UI pickers."""
    return sorted(MODULE_ACTIONS.items(), key=lambda kv: kv[1].lower())
