"""ICS-214 unit log router (MongoDB-backed).

Streams are stored as documents in ics_214_logs; entries are embedded arrays.
The idempotency_hash field prevents duplicate entries during auto-ingestion.
"""

from __future__ import annotations

import hashlib
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, HTTPException
from pydantic import BaseModel, Field

from sarapp_db.mongo.collection_names import IncidentCollections
from sarapp_db.mongo.database_manager import get_incident_db

router = APIRouter()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _new_id() -> str:
    return str(uuid.uuid4())


def _col(incident_id: str):
    return get_incident_db(incident_id)[IncidentCollections.ICS_214_LOGS]


def _map_stream(doc: Dict[str, Any], include_entries: bool = False) -> Dict[str, Any]:
    result: Dict[str, Any] = {
        "id": doc.get("stream_id") or doc.get("_id", ""),
        "incident_id": doc.get("incident_id", ""),
        "name": doc.get("name", ""),
        "op_number": doc.get("op_number", 0),
        "kind": doc.get("kind"),
        "section": doc.get("section"),
        "created_at": doc.get("created_at", ""),
        "updated_at": doc.get("updated_at", ""),
    }
    if include_entries:
        result["entries"] = [_map_entry(e) for e in (doc.get("entries") or [])]
    return result


def _map_entry(e: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "id": e.get("id", ""),
        "stream_id": e.get("stream_id", ""),
        "timestamp_utc": e.get("timestamp_utc", ""),
        "text": e.get("text", ""),
        "source": e.get("source", "manual"),
        "actor_user_id": e.get("actor_user_id"),
        "autogenerated": bool(e.get("autogenerated", False)),
        "critical_flag": bool(e.get("critical_flag", False)),
        "idempotency_hash": e.get("idempotency_hash", ""),
        "tags": e.get("tags") or [],
    }


# ===========================================================================
# STREAMS
# ===========================================================================

class StreamCreate(BaseModel):
    incident_id: str
    name: str
    op_number: int = 0
    kind: Optional[str] = None
    section: Optional[str] = None


class StreamUpdate(BaseModel):
    name: Optional[str] = None
    op_number: Optional[int] = None
    kind: Optional[str] = None
    section: Optional[str] = None


@router.get("/incidents/{incident_id}/ics214/streams")
def list_streams(incident_id: str):
    col = _col(incident_id)
    docs = list(col.find({"incident_id": incident_id}, {"entries": 0}).sort("created_at", 1))
    return [_map_stream(d) for d in docs]


@router.post("/incidents/{incident_id}/ics214/streams", status_code=201)
def create_stream(incident_id: str, data: StreamCreate):
    col = _col(incident_id)
    stream_id = _new_id()
    now = _utcnow()
    doc = {
        "_id": stream_id,
        "stream_id": stream_id,
        "incident_id": incident_id,
        "name": data.name,
        "op_number": data.op_number,
        "kind": data.kind,
        "section": data.section,
        "created_at": now,
        "updated_at": now,
        "entries": [],
    }
    col.insert_one(doc)
    return _map_stream(doc)


@router.get("/incidents/{incident_id}/ics214/streams/{stream_id}")
def get_stream(incident_id: str, stream_id: str):
    col = _col(incident_id)
    doc = col.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")
    return _map_stream(doc, include_entries=True)


@router.put("/incidents/{incident_id}/ics214/streams/{stream_id}")
def update_stream(incident_id: str, stream_id: str, data: StreamUpdate):
    col = _col(incident_id)
    updates: Dict[str, Any] = {"updated_at": _utcnow()}
    for field in ("name", "op_number", "kind", "section"):
        val = getattr(data, field, None)
        if val is not None:
            updates[field] = val
    result = col.find_one_and_update(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$set": updates},
        return_document=True,
        projection={"entries": 0},
    )
    if not result:
        raise HTTPException(status_code=404, detail="Stream not found")
    return _map_stream(result)


# ===========================================================================
# ENTRIES
# ===========================================================================

class EntryCreate(BaseModel):
    text: str
    timestamp_utc: Optional[str] = None
    critical_flag: bool = False
    tags: List[str] = Field(default_factory=list)
    source: str = "manual"
    actor_user_id: Optional[str] = None


class EntryUpdate(BaseModel):
    text: Optional[str] = None
    critical_flag: Optional[bool] = None
    tags: Optional[List[str]] = None


@router.get("/incidents/{incident_id}/ics214/streams/{stream_id}/entries")
def list_entries(incident_id: str, stream_id: str, exclude_internal: bool = False):
    col = _col(incident_id)
    doc = col.find_one({"stream_id": stream_id, "incident_id": incident_id}, {"entries": 1})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")
    entries = sorted(doc.get("entries") or [], key=lambda e: e.get("timestamp_utc", ""))
    if exclude_internal:
        entries = [e for e in entries if e.get("source") != "internal"]
    return [_map_entry(e) for e in entries]


@router.post("/incidents/{incident_id}/ics214/streams/{stream_id}/entries", status_code=201)
def add_entry(incident_id: str, stream_id: str, data: EntryCreate, autogenerated: bool = False, idempotency_hash: Optional[str] = None):
    col = _col(incident_id)
    doc = col.find_one({"stream_id": stream_id, "incident_id": incident_id}, {"entries.idempotency_hash": 1})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")

    ts = data.timestamp_utc or _utcnow()
    if not idempotency_hash:
        hash_input = f"manual:{uuid.uuid4()}".encode()
        idempotency_hash = hashlib.sha256(hash_input).hexdigest()

    # Idempotency check
    existing_hashes = {e.get("idempotency_hash") for e in (doc.get("entries") or [])}
    if idempotency_hash in existing_hashes:
        # Return the existing entry
        full = col.find_one({"stream_id": stream_id}, {"entries": 1})
        for e in (full or {}).get("entries", []):
            if e.get("idempotency_hash") == idempotency_hash:
                return _map_entry(e)
        raise HTTPException(status_code=409, detail="Duplicate entry")

    entry = {
        "id": _new_id(),
        "stream_id": stream_id,
        "timestamp_utc": ts,
        "text": data.text,
        "source": data.source,
        "actor_user_id": data.actor_user_id,
        "autogenerated": autogenerated,
        "critical_flag": data.critical_flag,
        "idempotency_hash": idempotency_hash,
        "tags": data.tags or [],
    }
    col.update_one(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$push": {"entries": entry}, "$set": {"updated_at": _utcnow()}},
    )
    return _map_entry(entry)


@router.put("/incidents/{incident_id}/ics214/streams/{stream_id}/entries/{entry_id}")
def update_entry(incident_id: str, stream_id: str, entry_id: str, data: EntryUpdate):
    col = _col(incident_id)
    doc = col.find_one({"stream_id": stream_id, "incident_id": incident_id}, {"entries": 1})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")

    entries = doc.get("entries") or []
    idx = next((i for i, e in enumerate(entries) if e.get("id") == entry_id), None)
    if idx is None:
        raise HTTPException(status_code=404, detail="Entry not found")

    updates: Dict[str, Any] = {}
    if data.text is not None:
        updates[f"entries.{idx}.text"] = data.text
    if data.critical_flag is not None:
        updates[f"entries.{idx}.critical_flag"] = data.critical_flag
    if data.tags is not None:
        updates[f"entries.{idx}.tags"] = data.tags
    updates["updated_at"] = _utcnow()

    col.update_one({"stream_id": stream_id, "incident_id": incident_id}, {"$set": updates})
    updated_doc = col.find_one({"stream_id": stream_id}, {"entries": 1})
    updated_entries = updated_doc.get("entries") or []
    entry = next((e for e in updated_entries if e.get("id") == entry_id), None)
    if not entry:
        raise HTTPException(status_code=404, detail="Entry not found after update")
    return _map_entry(entry)


@router.delete("/incidents/{incident_id}/ics214/streams/{stream_id}/entries/{entry_id}", status_code=204)
def delete_entry(incident_id: str, stream_id: str, entry_id: str):
    col = _col(incident_id)
    result = col.update_one(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$pull": {"entries": {"id": entry_id}}, "$set": {"updated_at": _utcnow()}},
    )
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Stream not found")


# ===========================================================================
# INGEST (event-driven auto-entry creation)
# ===========================================================================

class IngestRuleCreate(BaseModel):
    topic: str
    template: str
    enabled: bool = True


@router.get("/incidents/{incident_id}/ics214/ingest-rules")
def list_ingest_rules(incident_id: str, stream_id: Optional[str] = None):
    col = _col(incident_id)
    query: Dict[str, Any] = {"incident_id": incident_id}
    if stream_id:
        query["stream_id"] = stream_id
    docs = list(col.find(query, {"ingest_rules": 1, "stream_id": 1}))
    result = []
    for d in docs:
        sid = d.get("stream_id", "")
        for rule in (d.get("ingest_rules") or []):
            result.append({**rule, "stream_id": sid})
    return result


@router.post("/incidents/{incident_id}/ics214/streams/{stream_id}/ingest-rules", status_code=201)
def add_ingest_rule(incident_id: str, stream_id: str, data: IngestRuleCreate):
    col = _col(incident_id)
    rule = {
        "id": _new_id(),
        "stream_id": stream_id,
        "topic": data.topic,
        "template": data.template,
        "enabled": data.enabled,
    }
    col.update_one(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$push": {"ingest_rules": rule}},
    )
    return rule


@router.post("/incidents/{incident_id}/ics214/ingest-event")
def ingest_event(incident_id: str, event: Dict[str, Any] = Body(...)):
    col = _col(incident_id)
    topic = event.get("topic", "")
    created = []
    docs = list(col.find({"incident_id": incident_id}, {"stream_id": 1, "ingest_rules": 1, "entries.idempotency_hash": 1}))
    for doc in docs:
        stream_id = doc.get("stream_id", "")
        for rule in (doc.get("ingest_rules") or []):
            if not rule.get("enabled") or rule.get("topic") != topic:
                continue
            try:
                text = rule["template"].format(**event.get("payload", {}))
            except KeyError:
                continue
            hash_input = (event.get("event_id", "") + stream_id).encode()
            id_hash = hashlib.sha256(hash_input).hexdigest()
            existing = {e.get("idempotency_hash") for e in (doc.get("entries") or [])}
            if id_hash in existing:
                continue
            entry = {
                "id": _new_id(),
                "stream_id": stream_id,
                "timestamp_utc": _utcnow(),
                "text": text,
                "source": "auto",
                "actor_user_id": None,
                "autogenerated": True,
                "critical_flag": False,
                "idempotency_hash": id_hash,
                "tags": [],
            }
            col.update_one(
                {"stream_id": stream_id, "incident_id": incident_id},
                {"$push": {"entries": entry}, "$set": {"updated_at": _utcnow()}},
            )
            created.append(_map_entry(entry))
    return {"created": created}


# ===========================================================================
# SUBJECT OPTIONS (read-only lookup; falls back to empty if source tables
# not yet migrated for teams/personnel/org)
# ===========================================================================

@router.get("/incidents/{incident_id}/ics214/subject-options")
def list_subject_options(incident_id: str):
    return {"team": [], "individual": [], "section": [], "facility": []}
