"""ICS-214 unit log router (MongoDB-backed).

Streams are stored as documents in ics_214_logs; entries are embedded arrays.
The idempotency_hash field prevents duplicate entries during auto-ingestion.
"""

from __future__ import annotations

import hashlib
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, HTTPException
from pydantic import BaseModel, Field

from sarapp_db.mongo.collection_names import IncidentCollections
from sarapp_db.mongo.database_manager import get_incident_db, get_incident_db_name
from sarapp_db.mongo.mongo_client import get_client
from sarapp_db.mongo.repository import BaseRepository

router = APIRouter()


# ---------------------------------------------------------------------------
# Repository
# ---------------------------------------------------------------------------

class Ics214StreamsRepository(BaseRepository):
    collection_name = IncidentCollections.ICS_214_LOGS
    # Streams have no `deleted` field; they are never soft- or hard-deleted
    # via this router (only closed/opened via status).
    soft_deletes = False


def _streams_repo(incident_id: str) -> Ics214StreamsRepository:
    return Ics214StreamsRepository(get_incident_db(incident_id))


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _new_id() -> str:
    return str(uuid.uuid4())


def _map_stream(doc: Dict[str, Any], include_entries: bool = False) -> Dict[str, Any]:
    result: Dict[str, Any] = {
        "id": doc.get("stream_id") or doc.get("_id", ""),
        "incident_id": doc.get("incident_id", ""),
        "name": doc.get("name", ""),
        "op_number": doc.get("op_number", 0),
        "kind": doc.get("kind"),
        "section": doc.get("section"),
        "status": doc.get("status", "open"),
        "closed_at": doc.get("closed_at"),
        "created_at": doc.get("created_at", ""),
        "updated_at": doc.get("updated_at", ""),
    }
    if include_entries:
        result["entries"] = [_map_entry(e) for e in (doc.get("entries") or [])]
    return result


def _map_entry(e: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "id": e.get("id", ""),
        "stream_id": e.get("stream_id", ""),
        "timestamp_utc": e.get("timestamp_utc", ""),
        "text": e.get("text", ""),
        "source": e.get("source", "manual"),
        "actor_user_id": e.get("actor_user_id"),
        "autogenerated": bool(e.get("autogenerated", False)),
        "critical_flag": bool(e.get("critical_flag", False)),
        "idempotency_hash": e.get("idempotency_hash", ""),
        "tags": e.get("tags") or [],
    }


# ===========================================================================
# STREAMS
# ===========================================================================

class StreamCreate(BaseModel):
    incident_id: str
    name: str
    op_number: int = 0
    kind: Optional[str] = None
    section: Optional[str] = None


class StreamUpdate(BaseModel):
    name: Optional[str] = None
    op_number: Optional[int] = None
    kind: Optional[str] = None
    section: Optional[str] = None


@router.get("/incidents/{incident_id}/ics214/streams")
def list_streams(incident_id: str):
    repo = _streams_repo(incident_id)
    docs = repo._col.find({"incident_id": incident_id}, {"entries": 0}).sort("created_at", 1)
    return [_map_stream(d) for d in docs]


@router.post("/incidents/{incident_id}/ics214/streams", status_code=201)
def create_stream(incident_id: str, data: StreamCreate):
    repo = _streams_repo(incident_id)
    stream_id = _new_id()
    doc = {
        "_id": stream_id,
        "stream_id": stream_id,
        "incident_id": incident_id,
        "name": data.name,
        "op_number": data.op_number,
        "kind": data.kind,
        "section": data.section,
        "status": "open",
        "entries": [],
    }
    doc = repo.insert_one(doc)
    return _map_stream(doc)


@router.get("/incidents/{incident_id}/ics214/streams/{stream_id}")
def get_stream(incident_id: str, stream_id: str):
    repo = _streams_repo(incident_id)
    doc = repo.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")
    return _map_stream(doc, include_entries=True)


@router.put("/incidents/{incident_id}/ics214/streams/{stream_id}")
def update_stream(incident_id: str, stream_id: str, data: StreamUpdate):
    repo = _streams_repo(incident_id)
    updates: Dict[str, Any] = {}
    for field in ("name", "op_number", "kind", "section"):
        val = getattr(data, field, None)
        if val is not None:
            updates[field] = val
    doc = repo.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")
    repo.update_one(doc["_id"], updates, extra_filter={"incident_id": incident_id})
    result = repo.find_by_id(doc["_id"])
    return _map_stream(result)


class StreamStatusUpdate(BaseModel):
    status: str


@router.patch("/incidents/{incident_id}/ics214/streams/{stream_id}/status")
def set_stream_status(incident_id: str, stream_id: str, data: StreamStatusUpdate):
    if data.status not in ("open", "closed"):
        raise HTTPException(status_code=400, detail="status must be 'open' or 'closed'")
    repo = _streams_repo(incident_id)
    doc = repo.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")
    updates: Dict[str, Any] = {"status": data.status}
    updates["closed_at"] = _utcnow() if data.status == "closed" else None
    repo.update_one(doc["_id"], updates, extra_filter={"incident_id": incident_id})
    result = repo.find_by_id(doc["_id"])
    return _map_stream(result)


# ===========================================================================
# ENTRIES
# ===========================================================================

class EntryCreate(BaseModel):
    text: str
    timestamp_utc: Optional[str] = None
    critical_flag: bool = False
    tags: List[str] = Field(default_factory=list)
    source: str = "manual"
    actor_user_id: Optional[str] = None


class EntryUpdate(BaseModel):
    text: Optional[str] = None
    critical_flag: Optional[bool] = None
    tags: Optional[List[str]] = None


@router.get("/incidents/{incident_id}/ics214/streams/{stream_id}/entries")
def list_entries(incident_id: str, stream_id: str, exclude_internal: bool = False):
    repo = _streams_repo(incident_id)
    doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id}, {"entries": 1})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")
    entries = sorted(doc.get("entries") or [], key=lambda e: e.get("timestamp_utc", ""))
    if exclude_internal:
        entries = [e for e in entries if e.get("source") != "internal"]
    return [_map_entry(e) for e in entries]


@router.post("/incidents/{incident_id}/ics214/streams/{stream_id}/entries", status_code=201)
def add_entry(incident_id: str, stream_id: str, data: EntryCreate, autogenerated: bool = False, idempotency_hash: Optional[str] = None):
    repo = _streams_repo(incident_id)
    doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id}, {"entries.idempotency_hash": 1})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")

    ts = data.timestamp_utc or _utcnow()
    if not idempotency_hash:
        hash_input = f"manual:{uuid.uuid4()}".encode()
        idempotency_hash = hashlib.sha256(hash_input).hexdigest()

    # Idempotency check
    existing_hashes = {e.get("idempotency_hash") for e in (doc.get("entries") or [])}
    if idempotency_hash in existing_hashes:
        # Return the existing entry
        full = repo._col.find_one({"stream_id": stream_id}, {"entries": 1})
        for e in (full or {}).get("entries", []):
            if e.get("idempotency_hash") == idempotency_hash:
                return _map_entry(e)
        raise HTTPException(status_code=409, detail="Duplicate entry")

    entry = {
        "id": _new_id(),
        "stream_id": stream_id,
        "timestamp_utc": ts,
        "text": data.text,
        "source": data.source,
        "actor_user_id": data.actor_user_id,
        "autogenerated": autogenerated,
        "critical_flag": data.critical_flag,
        "idempotency_hash": idempotency_hash,
        "tags": data.tags or [],
    }
    repo._col.update_one(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$push": {"entries": entry}, "$set": {"updated_at": _utcnow()}},
    )
    updated_doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if updated_doc:
        repo._broadcast("updated", updated_doc["_id"], updated_doc)
    return _map_entry(entry)


@router.put("/incidents/{incident_id}/ics214/streams/{stream_id}/entries/{entry_id}")
def update_entry(incident_id: str, stream_id: str, entry_id: str, data: EntryUpdate):
    repo = _streams_repo(incident_id)
    doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id}, {"entries": 1})
    if not doc:
        raise HTTPException(status_code=404, detail="Stream not found")

    entries = doc.get("entries") or []
    idx = next((i for i, e in enumerate(entries) if e.get("id") == entry_id), None)
    if idx is None:
        raise HTTPException(status_code=404, detail="Entry not found")

    updates: Dict[str, Any] = {}
    if data.text is not None:
        updates[f"entries.{idx}.text"] = data.text
    if data.critical_flag is not None:
        updates[f"entries.{idx}.critical_flag"] = data.critical_flag
    if data.tags is not None:
        updates[f"entries.{idx}.tags"] = data.tags
    updates["updated_at"] = _utcnow()

    repo._col.update_one({"stream_id": stream_id, "incident_id": incident_id}, {"$set": updates})
    updated_doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if updated_doc:
        repo._broadcast("updated", updated_doc["_id"], updated_doc)
    updated_entries = (updated_doc or {}).get("entries") or []
    entry = next((e for e in updated_entries if e.get("id") == entry_id), None)
    if not entry:
        raise HTTPException(status_code=404, detail="Entry not found after update")
    return _map_entry(entry)


@router.delete("/incidents/{incident_id}/ics214/streams/{stream_id}/entries/{entry_id}", status_code=204)
def delete_entry(incident_id: str, stream_id: str, entry_id: str):
    repo = _streams_repo(incident_id)
    result = repo._col.update_one(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$pull": {"entries": {"id": entry_id}}, "$set": {"updated_at": _utcnow()}},
    )
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Stream not found")
    updated_doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if updated_doc:
        repo._broadcast("updated", updated_doc["_id"], updated_doc)


# ===========================================================================
# INGEST (event-driven auto-entry creation)
# ===========================================================================

class IngestRuleCreate(BaseModel):
    topic: str
    template: str
    enabled: bool = True


@router.get("/incidents/{incident_id}/ics214/ingest-rules")
def list_ingest_rules(incident_id: str, stream_id: Optional[str] = None):
    repo = _streams_repo(incident_id)
    query: Dict[str, Any] = {"incident_id": incident_id}
    if stream_id:
        query["stream_id"] = stream_id
    docs = list(repo._col.find(query, {"ingest_rules": 1, "stream_id": 1}))
    result = []
    for d in docs:
        sid = d.get("stream_id", "")
        for rule in (d.get("ingest_rules") or []):
            result.append({**rule, "stream_id": sid})
    return result


@router.post("/incidents/{incident_id}/ics214/streams/{stream_id}/ingest-rules", status_code=201)
def add_ingest_rule(incident_id: str, stream_id: str, data: IngestRuleCreate):
    repo = _streams_repo(incident_id)
    rule = {
        "id": _new_id(),
        "stream_id": stream_id,
        "topic": data.topic,
        "template": data.template,
        "enabled": data.enabled,
    }
    repo._col.update_one(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$push": {"ingest_rules": rule}},
    )
    updated_doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if updated_doc:
        repo._broadcast("updated", updated_doc["_id"], updated_doc)
    return rule


@router.post("/incidents/{incident_id}/ics214/ingest-event")
def ingest_event(incident_id: str, event: Dict[str, Any] = Body(...)):
    repo = _streams_repo(incident_id)
    topic = event.get("topic", "")
    created = []
    docs = list(repo._col.find({"incident_id": incident_id}, {"stream_id": 1, "ingest_rules": 1, "entries.idempotency_hash": 1}))
    for doc in docs:
        stream_id = doc.get("stream_id", "")
        for rule in (doc.get("ingest_rules") or []):
            if not rule.get("enabled") or rule.get("topic") != topic:
                continue
            try:
                text = rule["template"].format(**event.get("payload", {}))
            except KeyError:
                continue
            hash_input = (event.get("event_id", "") + stream_id).encode()
            id_hash = hashlib.sha256(hash_input).hexdigest()
            existing = {e.get("idempotency_hash") for e in (doc.get("entries") or [])}
            if id_hash in existing:
                continue
            entry = {
                "id": _new_id(),
                "stream_id": stream_id,
                "timestamp_utc": _utcnow(),
                "text": text,
                "source": "auto",
                "actor_user_id": None,
                "autogenerated": True,
                "critical_flag": False,
                "idempotency_hash": id_hash,
                "tags": [],
            }
            repo._col.update_one(
                {"stream_id": stream_id, "incident_id": incident_id},
                {"$push": {"entries": entry}, "$set": {"updated_at": _utcnow()}},
            )
            updated_doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id})
            if updated_doc:
                repo._broadcast("updated", updated_doc["_id"], updated_doc)
            created.append(_map_entry(entry))
    return {"created": created}


# ===========================================================================
# SUBJECT OPTIONS (read-only lookup; falls back to empty if source tables
# not yet migrated for teams/personnel/org)
# ===========================================================================

@router.get("/incidents/{incident_id}/ics214/subject-options")
def list_subject_options(incident_id: str):
    return {"team": [], "individual": [], "section": [], "facility": []}


# ===========================================================================
# MOBILE API — simplified team log endpoints for the mobile app
#
# Mobile clients interact with team logs through these endpoints only.
# They never need to know about stream IDs or the find-or-create pattern.
#
# Entries posted from mobile use source="mobile" so the desktop can
# distinguish them from system-generated ("auto") and manual desktop entries.
#
# URL pattern:  /api/incidents/{incident_id}/mobile/teams/{team_id}/log
# ===========================================================================

class MobileLogEntryCreate(BaseModel):
    text: str
    actor_user_id: Optional[str] = None
    timestamp_utc: Optional[str] = None
    critical_flag: bool = False
    tags: List[str] = Field(default_factory=list)


def _get_or_create_team_stream(repo: Ics214StreamsRepository, incident_id: str, team_id: int) -> Dict[str, Any]:
    """Find the ICS-214 stream for a team, creating it if it doesn't exist."""
    stream_name = f"Team {team_id}"
    doc = repo._col.find_one(
        {
            "incident_id": incident_id,
            "$or": [
                {"section": {"$regex": f'"ref": "team:{team_id}"'}},
                {"name": stream_name},
            ],
        },
        {"entries": 0},
    )
    if doc:
        return doc

    import json as _json
    section = _json.dumps({"category": "team", "ref": f"team:{team_id}", "label": stream_name})
    new_doc = {
        "stream_id": _new_id(),
        "incident_id": incident_id,
        "name": stream_name,
        "op_number": 0,
        "kind": "team",
        "section": section,
        "entries": [],
    }
    new_doc["_id"] = new_doc["stream_id"]
    new_doc = repo.insert_one(new_doc)
    return new_doc


@router.post("/incidents/{incident_id}/mobile/teams/{team_id}/log", status_code=201, tags=["mobile"])
def mobile_add_team_log_entry(incident_id: str, team_id: int, data: MobileLogEntryCreate):
    """Add a log entry to a team's ICS-214 stream from the mobile app.

    The stream is created automatically if it doesn't exist yet.
    The entry is tagged source='mobile' so desktop clients can identify it.
    """
    repo = _streams_repo(incident_id)
    stream = _get_or_create_team_stream(repo, incident_id, team_id)
    stream_id = stream["stream_id"]

    ts = data.timestamp_utc or _utcnow()
    hash_input = f"mobile:{stream_id}:{ts}:{data.text[:64]}".encode()
    idempotency_hash = hashlib.sha256(hash_input).hexdigest()

    existing_hashes = {e.get("idempotency_hash") for e in (stream.get("entries") or [])}
    if idempotency_hash in existing_hashes:
        full = repo._col.find_one({"stream_id": stream_id}, {"entries": 1})
        for e in (full or {}).get("entries", []):
            if e.get("idempotency_hash") == idempotency_hash:
                return _map_entry(e)

    entry = {
        "id": _new_id(),
        "stream_id": stream_id,
        "timestamp_utc": ts,
        "text": data.text,
        "source": "mobile",
        "actor_user_id": data.actor_user_id,
        "autogenerated": False,
        "critical_flag": data.critical_flag,
        "idempotency_hash": idempotency_hash,
        "tags": data.tags or [],
    }
    repo._col.update_one(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$push": {"entries": entry}, "$set": {"updated_at": _utcnow()}},
    )
    updated_doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if updated_doc:
        repo._broadcast("updated", updated_doc["_id"], updated_doc)
    return _map_entry(entry)


@router.get("/incidents/{incident_id}/mobile/teams/{team_id}/log", tags=["mobile"])
def mobile_get_team_log(incident_id: str, team_id: int, since: Optional[str] = None):
    """Return log entries for a team's ICS-214 stream.

    - Excludes source='internal' (composition noise — not relevant to field teams).
    - Optional `since` param (ISO timestamp) returns only entries after that time,
      useful for polling/delta sync on the mobile side.
    """
    repo = _streams_repo(incident_id)
    stream = _get_or_create_team_stream(repo, incident_id, team_id)
    stream_id = stream["stream_id"]

    full = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id}, {"entries": 1})
    entries = sorted(
        (full or {}).get("entries") or [],
        key=lambda e: e.get("timestamp_utc", ""),
    )
    entries = [e for e in entries if e.get("source") != "internal"]
    if since:
        entries = [e for e in entries if e.get("timestamp_utc", "") > since]
    return [_map_entry(e) for e in entries]


@router.delete(
    "/incidents/{incident_id}/mobile/teams/{team_id}/log/{entry_id}",
    status_code=204,
    tags=["mobile"],
)
def mobile_delete_team_log_entry(incident_id: str, team_id: int, entry_id: str):
    """Delete a log entry by id.  Only the entry's author should call this."""
    repo = _streams_repo(incident_id)
    stream = _get_or_create_team_stream(repo, incident_id, team_id)
    stream_id = stream["stream_id"]
    repo._col.update_one(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$pull": {"entries": {"id": entry_id}}, "$set": {"updated_at": _utcnow()}},
    )
    updated_doc = repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if updated_doc:
        repo._broadcast("updated", updated_doc["_id"], updated_doc)


class MobileNarrativeCreate(BaseModel):
    text: str
    actor_user_id: Optional[str] = None
    timestamp_utc: Optional[str] = None
    critical_flag: bool = False


class _TasksRepository(BaseRepository):
    collection_name = IncidentCollections.OPERATIONS_TASKS


def _tasks_repo(incident_id: str) -> _TasksRepository:
    return _TasksRepository(get_client()[get_incident_db_name(incident_id)])


@router.post(
    "/incidents/{incident_id}/mobile/teams/{team_id}/tasks/{task_id}/narrative",
    status_code=201,
    tags=["mobile"],
)
def mobile_add_task_narrative(
    incident_id: str, team_id: int, task_id: int, data: MobileNarrativeCreate
):
    """Add a narrative entry to a task from the mobile app.

    The entry is stored in the task's narrative array (source='mobile') and
    automatically mirrored to the team's ICS-214 stream so it appears on the
    formal 214 form.
    """
    tasks_repo = _tasks_repo(incident_id)
    ts = data.timestamp_utc or _utcnow()
    narrative_entry = {
        "id": _new_id(),
        "timestamp": ts,
        "narrative": data.text,
        "entered_by": data.actor_user_id or "",
        "team_id": team_id,
        "team_num": f"Team {team_id}",
        "critical": data.critical_flag,
        "source": "mobile",
    }
    result = tasks_repo._col.find_one_and_update(
        {"int_id": task_id},
        {"$push": {"narrative": narrative_entry}},
        projection={"int_id": 1, "title": 1},
    )
    if not result:
        raise HTTPException(status_code=404, detail="Task not found")
    updated_task = tasks_repo._col.find_one({"int_id": task_id})
    if updated_task:
        tasks_repo._broadcast("updated", updated_task["_id"], updated_task)

    # Mirror to team's ICS-214 stream
    ics_repo = _streams_repo(incident_id)
    stream = _get_or_create_team_stream(ics_repo, incident_id, team_id)
    stream_id = stream["stream_id"]
    critical_tag = " [CRITICAL]" if data.critical_flag else ""
    task_label = result.get("title") or f"Task {task_id}"
    log_text = f"[Task: {task_label}]{critical_tag} {data.text}"
    hash_input = f"mobile-narrative:{stream_id}:{ts}:{data.text[:64]}".encode()
    idempotency_hash = hashlib.sha256(hash_input).hexdigest()
    ics_entry = {
        "id": _new_id(),
        "stream_id": stream_id,
        "timestamp_utc": ts,
        "text": log_text[:500],
        "source": "mobile",
        "actor_user_id": data.actor_user_id,
        "autogenerated": False,
        "critical_flag": data.critical_flag,
        "idempotency_hash": idempotency_hash,
        "tags": ["narrative", f"task:{task_id}"],
    }
    ics_repo._col.update_one(
        {"stream_id": stream_id, "incident_id": incident_id},
        {"$push": {"entries": ics_entry}, "$set": {"updated_at": _utcnow()}},
    )
    updated_stream = ics_repo._col.find_one({"stream_id": stream_id, "incident_id": incident_id})
    if updated_stream:
        ics_repo._broadcast("updated", updated_stream["_id"], updated_stream)
    return {**narrative_entry, "ics214_entry_id": ics_entry["id"]}
