from __future__ import annotations

from .models import MeetingTemplate


ICS_MEETING_TEMPLATES: list[MeetingTemplate] = [
    MeetingTemplate(
        slug="objectives-meeting",
        name="Objectives Meeting",
        default_duration_minutes=45,
        agenda_sections=["Incident priorities", "Command emphasis", "End state", "Objective approval"],
        required_attendee_roles=["Incident Commander", "Planning Section Chief", "Operations Section Chief"],
        optional_attendee_roles=["Command Staff", "Agency Representatives"],
        prep_checklist_items=["Review current situation", "Prepare objective recommendations"],
        agenda_checklist_items=["Confirm command emphasis", "Approve operational objectives"],
        closeout_checklist_items=["Publish approved objectives", "Notify section leads of changes"],
    ),
    MeetingTemplate(
        slug="strategy-meeting",
        name="Strategy Meeting",
        default_duration_minutes=45,
        agenda_sections=["Situation analysis", "Strategic alternatives", "Constraints", "Recommended direction"],
        required_attendee_roles=["Incident Commander", "Operations Section Chief", "Planning Section Chief"],
        optional_attendee_roles=["Safety Officer", "Intel/Investigations Supervisor"],
        prep_checklist_items=["Gather field intelligence", "Review command emphasis"],
        agenda_checklist_items=["Compare strategic options", "Select recommended strategy"],
        closeout_checklist_items=["Route strategy decisions", "Prepare tactics input"],
    ),
    MeetingTemplate(
        slug="command-general-staff",
        name="Command and General Staff Meeting",
        default_duration_minutes=60,
        agenda_sections=["Commander's intent", "Section updates", "Constraints", "Open decisions"],
        required_attendee_roles=["Incident Commander", "Command Staff", "General Staff"],
        optional_attendee_roles=["Technical Specialists", "Agency Representatives"],
        prep_checklist_items=["Confirm section inputs", "Review current objectives"],
        agenda_checklist_items=["Capture decisions", "Confirm planning timeline"],
        closeout_checklist_items=["Route decisions to Planning log", "Update action owners"],
    ),
    MeetingTemplate(
        slug="tactics",
        name="Tactics Meeting",
        default_duration_minutes=45,
        agenda_sections=["Objectives", "Tactical assignments", "Resource needs", "Safety concerns"],
        required_attendee_roles=["Operations Section Chief", "Planning Section Chief", "Safety Officer"],
        optional_attendee_roles=["Logistics Section Chief", "Branch Directors"],
        prep_checklist_items=["Gather situation status", "Review resource availability"],
        agenda_checklist_items=["Validate tactics", "Identify resource shortfalls"],
        closeout_checklist_items=["Send resource gaps for follow-up", "Update draft ICS-215 inputs"],
    ),
    MeetingTemplate(
        slug="planning-prep",
        name="Planning Preparation Meeting",
        default_duration_minutes=30,
        agenda_sections=["Timeline review", "Worksheet owners", "Data needs", "Open blockers"],
        required_attendee_roles=["Planning Section Chief", "Resources Unit Leader", "Situation Unit Leader"],
        optional_attendee_roles=["Documentation Unit Leader", "Operations Section Chief"],
        prep_checklist_items=["Collect current planning status", "Review prior action items"],
        agenda_checklist_items=["Assign worksheet owners", "Confirm planning meeting inputs"],
        closeout_checklist_items=["Capture deadlines", "Follow up on missing inputs"],
    ),
    MeetingTemplate(
        slug="planning",
        name="Planning Meeting",
        default_duration_minutes=60,
        agenda_sections=["Situation review", "Objectives approval", "Plan components", "Deadlines"],
        required_attendee_roles=["Incident Commander", "Planning Section Chief", "Operations Section Chief"],
        optional_attendee_roles=["Logistics Section Chief", "Finance/Admin Section Chief"],
        prep_checklist_items=["Prepare proposed objectives", "Compile section plan inputs"],
        agenda_checklist_items=["Approve objectives", "Confirm IAP components"],
        closeout_checklist_items=["Assign IAP owners", "Publish planning timeline changes"],
    ),
    MeetingTemplate(
        slug="iap-prep-and-approval",
        name="IAP Preparation and Approval",
        default_duration_minutes=60,
        agenda_sections=["Document status", "Review forms set", "Approval issues", "Publication timeline"],
        required_attendee_roles=["Planning Section Chief", "Documentation Unit Leader", "Incident Commander"],
        optional_attendee_roles=["Operations Section Chief", "Safety Officer", "Logistics Section Chief"],
        prep_checklist_items=["Assemble IAP components", "Confirm latest approved objectives"],
        agenda_checklist_items=["Review IAP completeness", "Resolve approval comments"],
        closeout_checklist_items=["Approve final IAP", "Release IAP for distribution"],
    ),
    MeetingTemplate(
        slug="operations-briefing",
        name="Operational Period Briefing",
        default_duration_minutes=30,
        agenda_sections=["Current situation", "Assignments", "Communications", "Safety message"],
        required_attendee_roles=["Operations Section Chief", "Supervisors", "Safety Officer"],
        optional_attendee_roles=["Incident Commander", "Liaison Officer"],
        prep_checklist_items=["Finalize assignment materials", "Confirm briefing location"],
        agenda_checklist_items=["Brief assignments", "Brief safety and communications"],
        closeout_checklist_items=["Record attendance", "Capture late changes"],
    ),
    MeetingTemplate(
        slug="safety-briefing",
        name="Safety Briefing",
        default_duration_minutes=20,
        agenda_sections=["Hazards", "Controls", "Emergency procedures", "Questions"],
        required_attendee_roles=["Safety Officer", "Operations Supervisors"],
        optional_attendee_roles=["Medical Unit Leader"],
        prep_checklist_items=["Review current hazards", "Prepare safety message"],
        agenda_checklist_items=["Brief controls", "Confirm emergency procedures"],
        closeout_checklist_items=["Route safety items to log", "Update safety documentation"],
    ),
    MeetingTemplate(
        slug="logistics",
        name="Logistics Meeting",
        default_duration_minutes=45,
        agenda_sections=["Facilities", "Supply", "Communications", "Medical support", "Transportation"],
        required_attendee_roles=["Logistics Section Chief", "Service Branch Director", "Support Branch Director"],
        optional_attendee_roles=["Operations Section Chief", "Planning Section Chief"],
        prep_checklist_items=["Review open resource requests", "Confirm support constraints"],
        agenda_checklist_items=["Prioritize support needs", "Identify delivery blockers"],
        closeout_checklist_items=["Update resource request status", "Assign follow-up owners"],
    ),
    MeetingTemplate(
        slug="finance-admin",
        name="Finance/Admin Meeting",
        default_duration_minutes=45,
        agenda_sections=["Time", "Procurement", "Compensation/claims", "Cost tracking"],
        required_attendee_roles=["Finance/Admin Section Chief"],
        optional_attendee_roles=["Logistics Section Chief", "Agency Representatives"],
        prep_checklist_items=["Review cost data", "Collect procurement issues"],
        agenda_checklist_items=["Resolve approval blockers", "Confirm documentation needs"],
        closeout_checklist_items=["Route fiscal decisions", "Update approval queue"],
    ),
    MeetingTemplate(
        slug="demobilization",
        name="Demobilization Meeting",
        default_duration_minutes=45,
        agenda_sections=["Release priorities", "Travel", "Accountability", "Documentation"],
        required_attendee_roles=["Demobilization Unit Leader", "Planning Section Chief", "Logistics Section Chief"],
        optional_attendee_roles=["Operations Section Chief", "Finance/Admin Section Chief"],
        prep_checklist_items=["Review demobilization criteria", "Prepare release candidates"],
        agenda_checklist_items=["Confirm release process", "Identify special travel needs"],
        closeout_checklist_items=["Update demobilization plan", "Notify affected units"],
    ),
    MeetingTemplate(
        slug="public-information",
        name="Public Information Meeting",
        default_duration_minutes=30,
        agenda_sections=["Messages", "Media issues", "Approvals", "Release timing"],
        required_attendee_roles=["Public Information Officer"],
        optional_attendee_roles=["Incident Commander", "Liaison Officer", "Agency Representatives"],
        prep_checklist_items=["Collect draft messages", "Review approval requirements"],
        agenda_checklist_items=["Confirm key messages", "Identify rumor control needs"],
        closeout_checklist_items=["Route approved messages", "Track follow-up questions"],
    ),
    MeetingTemplate(
        slug="air-operations-branch",
        name="Air Operations Branch Meeting",
        default_duration_minutes=30,
        agenda_sections=["Aircraft status", "Mission priorities", "Airspace issues", "Safety concerns"],
        required_attendee_roles=["Air Operations Branch Director", "Operations Section Chief"],
        optional_attendee_roles=["Helibase Manager", "Air Support Group Supervisor", "Safety Officer"],
        prep_checklist_items=["Confirm aircraft availability", "Review air mission requests"],
        agenda_checklist_items=["Prioritize air resources", "Review air safety issues"],
        closeout_checklist_items=["Publish air assignments", "Route unmet requests for follow-up"],
    ),
    MeetingTemplate(
        slug="intel-investigations",
        name="Intel/Investigations Meeting",
        default_duration_minutes=45,
        agenda_sections=["Current leads", "Information gaps", "Debrief priorities", "Collection tasks"],
        required_attendee_roles=["Intel/Investigations Supervisor", "Planning Section Chief"],
        optional_attendee_roles=["Operations Section Chief", "Situation Unit Leader"],
        prep_checklist_items=["Compile lead status", "Gather debrief updates"],
        agenda_checklist_items=["Prioritize collections", "Assign intel follow-ups"],
        closeout_checklist_items=["Route significant intel", "Update situational products"],
    ),
]


__all__ = ["ICS_MEETING_TEMPLATES"]
