from __future__ import annotations

from .models import MeetingTemplate


ICS_MEETING_TEMPLATES: list[MeetingTemplate] = [
    MeetingTemplate(
        slug="command-general-staff",
        name="Command and General Staff Meeting",
        default_duration_minutes=60,
        agenda_sections=["Commander's intent", "Section updates", "Constraints", "Open decisions"],
        required_attendee_roles=["Incident Commander", "Command Staff", "General Staff"],
        optional_attendee_roles=["Technical Specialists", "Agency Representatives"],
        prep_checklist_items=["Confirm section inputs", "Review current objectives"],
        agenda_checklist_items=["Capture decisions", "Confirm planning timeline"],
        closeout_checklist_items=["Route decisions to Planning log", "Update action owners"],
    ),
    MeetingTemplate(
        slug="tactics",
        name="Tactics Meeting",
        default_duration_minutes=45,
        agenda_sections=["Objectives", "Tactical assignments", "Resource needs", "Safety concerns"],
        required_attendee_roles=["Operations Section Chief", "Planning Section Chief", "Safety Officer"],
        optional_attendee_roles=["Logistics Section Chief", "Branch Directors"],
        prep_checklist_items=["Gather situation status", "Review resource availability"],
        agenda_checklist_items=["Validate tactics", "Identify resource shortfalls"],
        closeout_checklist_items=["Send resource gaps for follow-up", "Update draft ICS-215 inputs"],
    ),
    MeetingTemplate(
        slug="planning",
        name="Planning Meeting",
        default_duration_minutes=60,
        agenda_sections=["Situation review", "Objectives approval", "Plan components", "Deadlines"],
        required_attendee_roles=["Incident Commander", "Planning Section Chief", "Operations Section Chief"],
        optional_attendee_roles=["Logistics Section Chief", "Finance/Admin Section Chief"],
        prep_checklist_items=["Prepare proposed objectives", "Compile section plan inputs"],
        agenda_checklist_items=["Approve objectives", "Confirm IAP components"],
        closeout_checklist_items=["Assign IAP owners", "Publish planning timeline changes"],
    ),
    MeetingTemplate(
        slug="operations-briefing",
        name="Operations Briefing",
        default_duration_minutes=30,
        agenda_sections=["Current situation", "Assignments", "Communications", "Safety message"],
        required_attendee_roles=["Operations Section Chief", "Supervisors", "Safety Officer"],
        optional_attendee_roles=["Incident Commander", "Liaison Officer"],
        prep_checklist_items=["Finalize assignment materials", "Confirm briefing location"],
        agenda_checklist_items=["Brief assignments", "Brief safety and communications"],
        closeout_checklist_items=["Record attendance", "Capture late changes"],
    ),
    MeetingTemplate(
        slug="safety-briefing",
        name="Safety Briefing",
        default_duration_minutes=20,
        agenda_sections=["Hazards", "Controls", "Emergency procedures", "Questions"],
        required_attendee_roles=["Safety Officer", "Operations Supervisors"],
        optional_attendee_roles=["Medical Unit Leader"],
        prep_checklist_items=["Review current hazards", "Prepare safety message"],
        agenda_checklist_items=["Brief controls", "Confirm emergency procedures"],
        closeout_checklist_items=["Route safety items to log", "Update safety documentation"],
    ),
    MeetingTemplate(
        slug="logistics",
        name="Logistics Meeting",
        default_duration_minutes=45,
        agenda_sections=["Facilities", "Supply", "Communications", "Medical support", "Transportation"],
        required_attendee_roles=["Logistics Section Chief", "Service Branch Director", "Support Branch Director"],
        optional_attendee_roles=["Operations Section Chief", "Planning Section Chief"],
        prep_checklist_items=["Review open resource requests", "Confirm support constraints"],
        agenda_checklist_items=["Prioritize support needs", "Identify delivery blockers"],
        closeout_checklist_items=["Update resource request status", "Assign follow-up owners"],
    ),
    MeetingTemplate(
        slug="finance-admin",
        name="Finance/Admin Meeting",
        default_duration_minutes=45,
        agenda_sections=["Time", "Procurement", "Compensation/claims", "Cost tracking"],
        required_attendee_roles=["Finance/Admin Section Chief"],
        optional_attendee_roles=["Logistics Section Chief", "Agency Representatives"],
        prep_checklist_items=["Review cost data", "Collect procurement issues"],
        agenda_checklist_items=["Resolve approval blockers", "Confirm documentation needs"],
        closeout_checklist_items=["Route fiscal decisions", "Update approval queue"],
    ),
    MeetingTemplate(
        slug="demobilization",
        name="Demobilization Meeting",
        default_duration_minutes=45,
        agenda_sections=["Release priorities", "Travel", "Accountability", "Documentation"],
        required_attendee_roles=["Demobilization Unit Leader", "Planning Section Chief", "Logistics Section Chief"],
        optional_attendee_roles=["Operations Section Chief", "Finance/Admin Section Chief"],
        prep_checklist_items=["Review demobilization criteria", "Prepare release candidates"],
        agenda_checklist_items=["Confirm release process", "Identify special travel needs"],
        closeout_checklist_items=["Update demobilization plan", "Notify affected units"],
    ),
    MeetingTemplate(
        slug="public-information",
        name="Public Information Meeting",
        default_duration_minutes=30,
        agenda_sections=["Messages", "Media issues", "Approvals", "Release timing"],
        required_attendee_roles=["Public Information Officer"],
        optional_attendee_roles=["Incident Commander", "Liaison Officer", "Agency Representatives"],
        prep_checklist_items=["Collect draft messages", "Review approval requirements"],
        agenda_checklist_items=["Confirm key messages", "Identify rumor control needs"],
        closeout_checklist_items=["Route approved messages", "Track follow-up questions"],
    ),
]


__all__ = ["ICS_MEETING_TEMPLATES"]
