from __future__ import annotations

from modules.operations.data import repository


class _FakeEntryCreate:
    def __init__(self, text: str, source: str, actor_user_id: str | None) -> None:
        self.text = text
        self.source = source
        self.actor_user_id = actor_user_id


def test_ics214_auto_entry_normalizes_integer_actor_user_id_to_string() -> None:
    recorded: dict[str, object] = {}

    class FakeIcs:
        @staticmethod
        def list_streams(inc: str) -> list[dict[str, object]]:
            assert inc == "INC-1"
            return [{"id": "stream-1", "section": '{"ref": "team:7"}', "name": "Team 7"}]

        @staticmethod
        def add_entry(inc: str, stream_id: str, entry: _FakeEntryCreate, autogenerated: bool) -> None:
            recorded["inc"] = inc
            recorded["stream_id"] = stream_id
            recorded["entry"] = entry
            recorded["autogenerated"] = autogenerated

    repository._ics214_auto_entry(
        "INC-1",
        category="team",
        ref_id=7,
        text="Team status changed to Assigned",
        ics=FakeIcs,
        EntryCreate=_FakeEntryCreate,
        StreamCreate=object,
        actor_user_id=186,
    )

    assert recorded["inc"] == "INC-1"
    assert recorded["stream_id"] == "stream-1"
    assert recorded["autogenerated"] is True
    entry = recorded["entry"]
    assert isinstance(entry, _FakeEntryCreate)
    assert entry.actor_user_id == "186"

