"""Seed demo data for ICS-214."""
from __future__ import annotations

from .schemas import StreamCreate, EntryCreate
from . import services


def seed(mission_id: str) -> None:
    ops_stream = services.create_stream(StreamCreate(mission_id=mission_id, name="Ops Section Log", op_number=1, section="Ops"))
    team_a = services.create_stream(StreamCreate(mission_id=mission_id, name="Team A", op_number=1, kind="team"))
    team_b = services.create_stream(StreamCreate(mission_id=mission_id, name="Team B", op_number=1, kind="team"))
    for i in range(5):
        services.add_entry(mission_id, ops_stream.id, EntryCreate(text=f"Manual entry {i}"))
    for i in range(5):
        services.add_entry(mission_id, team_a.id, EntryCreate(text=f"Auto entry {i}", source="auto"), autogenerated=True)
