"""Business logic for ICS-214 module (MongoDB-backed via SARApp API)."""
from __future__ import annotations

from typing import Dict, Any, List

from .schemas import EntryCreate, EntryUpdate, StreamCreate, StreamUpdate, ExportRequest


def _client():
    from utils.api_client import api_client
    return api_client


def can_read(user_id: str, stream) -> bool:
    return True


def can_write(user_id: str, stream) -> bool:
    return True


# Stream CRUD ----------------------------------------------------------------

def create_stream(data: StreamCreate):
    return _client().post(
        f"/api/incidents/{data.incident_id}/ics214/streams",
        json=data.model_dump(),
    )


def list_streams(incident_id: str) -> List[Dict[str, Any]]:
    return _client().get(f"/api/incidents/{incident_id}/ics214/streams")


def list_subject_options(incident_id: str) -> Dict[str, List[Dict[str, Any]]]:
    try:
        return _client().get(f"/api/incidents/{incident_id}/ics214/subject-options")
    except Exception:
        return {"team": [], "individual": [], "section": [], "facility": []}


def update_stream(incident_id: str, stream_id: str, data: StreamUpdate):
    return _client().put(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}",
        json=data.model_dump(exclude_unset=True),
    )


def set_stream_status(incident_id: str, stream_id: str, status: str) -> Dict[str, Any]:
    return _client().patch(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/status",
        json={"status": status},
    )


# Entries --------------------------------------------------------------------

def add_entry(
    incident_id: str,
    stream_id: str,
    data: EntryCreate,
    autogenerated: bool = False,
    id_hash: str | None = None,
) -> Dict[str, Any]:
    params: Dict[str, Any] = {"autogenerated": autogenerated}
    if id_hash:
        params["idempotency_hash"] = id_hash

    payload = data.model_dump()
    if payload.get("timestamp_utc") and not isinstance(payload["timestamp_utc"], str):
        payload["timestamp_utc"] = payload["timestamp_utc"].isoformat(timespec="seconds")

    return _client().post(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/entries",
        json=payload,
        params=params,
    )


def list_entries(incident_id: str, stream_id: str) -> List[Dict[str, Any]]:
    return _client().get(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/entries"
    )


def update_entry(incident_id: str, entry_id: str, data: "EntryUpdate", stream_id: str | None = None) -> Dict[str, Any] | None:
    if not isinstance(data, EntryUpdate):
        data = EntryUpdate(**(data or {}))
    if not stream_id:
        raise ValueError("stream_id is required for update_entry")
    return _client().put(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/entries/{entry_id}",
        json=data.model_dump(exclude_unset=True),
    )


def delete_entry(incident_id: str, entry_id: str, stream_id: str | None = None) -> bool:
    if not stream_id:
        raise ValueError("stream_id is required for delete_entry")
    try:
        _client().delete(
            f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/entries/{entry_id}",
        )
        return True
    except Exception:
        return False


# Event ingestion -------------------------------------------------------------

def add_ingest_rule(incident_id: str, stream_id: str, topic: str, template: str, enabled: bool = True) -> Dict[str, Any]:
    return _client().post(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/ingest-rules",
        json={"topic": topic, "template": template, "enabled": enabled},
    )


def ingest_event_to_entries(event: Dict[str, Any]) -> List[Dict[str, Any]]:
    incident_id = event["incident_id"]
    result = _client().post(
        f"/api/incidents/{incident_id}/ics214/ingest-event",
        json=event,
    )
    return result.get("created", [])


# Export ---------------------------------------------------------------------

def export_stream(incident_id: str, stream_id: str, options: ExportRequest):
    """Generate and save a PDF export of the stream as a proper ICS-214 form."""
    import uuid
    from datetime import datetime, timezone
    from pathlib import Path

    # Fetch entries, excluding internal composition notes from the printed form
    entries = _client().get(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/entries",
        params={"exclude_internal": True},
    )
    if not options.include_auto:
        entries = [e for e in entries if not e.get("autogenerated")]

    # Fetch stream metadata for header fields
    stream = _client().get(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}"
    )

    # Fetch incident metadata for header
    incident_name = ""
    op_date_from = op_date_to = op_time_from = op_time_to = ""
    try:
        inc = _client().get(f"/api/incidents/{incident_id}/ic-overview")
        incident_name = inc.get("incident_name") or inc.get("name") or incident_id
    except Exception:
        incident_name = incident_id

    try:
        op = _client().get(f"/api/incidents/{incident_id}/planning/operational-periods/active")
        if op:
            def _fmt_dt(iso: str, fmt: str) -> str:
                try:
                    return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime(fmt)
                except Exception:
                    return iso or ""
            op_date_from = _fmt_dt(op.get("date_from") or "", "%m/%d/%Y")
            op_date_to   = _fmt_dt(op.get("date_to")   or "", "%m/%d/%Y")
            op_time_from = _fmt_dt(op.get("time_from") or op.get("date_from") or "", "%H%MZ")
            op_time_to   = _fmt_dt(op.get("time_to")   or op.get("date_to")   or "", "%H%MZ")
    except Exception:
        pass

    # Build resources list from stream metadata
    resources = []
    try:
        import json as _json
        section = stream.get("section") or "{}"
        sec_data = _json.loads(section) if isinstance(section, str) else section
        team_id = None
        ref = sec_data.get("ref", "")
        if ref.startswith("team:"):
            team_id = ref.split(":", 1)[1]
        if team_id:
            teams = _client().get(f"/api/incidents/{incident_id}/operations/teams")
            for t in (teams or []):
                if str(t.get("int_id")) == str(team_id):
                    for m in (t.get("members") or []):
                        resources.append({
                            "name": m.get("name") or m.get("full_name") or "",
                            "ics_position": m.get("role") or m.get("ics_position") or "",
                            "home_agency": m.get("agency") or m.get("home_agency") or "",
                        })
                    break
    except Exception:
        pass

    # Prepared-by info from active user
    prepared_name = prepared_title = ""
    try:
        from utils.state import AppState
        uid = AppState.get_active_user_id()
        role = AppState.get_active_role()
        prepared_name = str(uid or "")
        prepared_title = str(role or "")
    except Exception:
        pass

    prepared_dt = datetime.now(timezone.utc).strftime("%m/%d/%Y %H%MZ")

    # Unit name from stream name
    unit_name = stream.get("name") or ""

    base_dir = Path("data") / "uploads" / "ics214" / incident_id
    base_dir.mkdir(parents=True, exist_ok=True)
    filename = f"ICS214_{stream_id}_{int(datetime.now(timezone.utc).timestamp())}.pdf"
    file_path = base_dir / filename

    _ASSETS = Path(__file__).parent / "assets"
    from modules.forms_creator.pdf_filler.pdf_filler import PDFFiller
    from modules.forms_creator.form_set_registry import FormSetRegistry
    filler = PDFFiller(_ASSETS / "ics214_mapping.json")
    registry = FormSetRegistry()
    form_def = registry.get_form_definition("ics_214")
    form_row_groups = form_def.row_groups if form_def else []

    formatted_entries = []
    for e in entries:
        ts_raw = e.get("timestamp_utc") or e.get("timestamp") or ""
        try:
            ts_dt = datetime.fromisoformat(str(ts_raw).replace("Z", "+00:00"))
            ts_display = ts_dt.strftime("%m/%d %H%MZ")
        except Exception:
            ts_display = str(ts_raw)[:14]
        formatted_entries.append({
            "timestamp_display": ts_display,
            "text": e.get("text") or e.get("activity") or "",
        })

    data = {
        "incident": {"name": incident_name},
        "op_period": {
            "date_from": op_date_from,
            "date_to": op_date_to,
            "time_from": op_time_from,
            "time_to": op_time_to,
        },
        "unit": {"name": unit_name, "ics_position": "", "home_agency": ""},
        "resources": resources,
        "entries": formatted_entries,
        "prepared": {
            "name": prepared_name,
            "title": prepared_title,
            "dt": prepared_dt,
        },
    }
    filler.fill(data, _ASSETS / "ics214_page1.pdf", file_path, form_row_groups=form_row_groups)

    class _ExportResult:
        def __init__(self, id_, file_path_, created_at_):
            self.id = id_
            self.file_path = str(file_path_)
            self.created_at = created_at_

    return _ExportResult(
        id_=str(uuid.uuid4()),
        file_path_=file_path,
        created_at_=datetime.now(timezone.utc),
    )
