"""Business logic for ICS-214 module (MongoDB-backed via SARApp API)."""
from __future__ import annotations

from typing import Dict, Any, List

from .schemas import EntryCreate, EntryUpdate, StreamCreate, StreamUpdate, ExportRequest


def _client():
    from utils.api_client import api_client
    return api_client


def can_read(user_id: str, stream) -> bool:
    return True


def can_write(user_id: str, stream) -> bool:
    return True


# Stream CRUD ----------------------------------------------------------------

def create_stream(data: StreamCreate):
    return _client().post(
        f"/api/incidents/{data.incident_id}/ics214/streams",
        json=data.model_dump(),
    )


def list_streams(incident_id: str) -> List[Dict[str, Any]]:
    return _client().get(f"/api/incidents/{incident_id}/ics214/streams")


def list_subject_options(incident_id: str) -> Dict[str, List[Dict[str, Any]]]:
    try:
        return _client().get(f"/api/incidents/{incident_id}/ics214/subject-options")
    except Exception:
        return {"team": [], "individual": [], "section": [], "facility": []}


def update_stream(incident_id: str, stream_id: str, data: StreamUpdate):
    return _client().put(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}",
        json=data.model_dump(exclude_unset=True),
    )


# Entries --------------------------------------------------------------------

def add_entry(
    incident_id: str,
    stream_id: str,
    data: EntryCreate,
    autogenerated: bool = False,
    id_hash: str | None = None,
) -> Dict[str, Any]:
    params: Dict[str, Any] = {"autogenerated": autogenerated}
    if id_hash:
        params["idempotency_hash"] = id_hash

    payload = data.model_dump()
    if payload.get("timestamp_utc") and not isinstance(payload["timestamp_utc"], str):
        payload["timestamp_utc"] = payload["timestamp_utc"].isoformat(timespec="seconds")

    return _client().post(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/entries",
        json=payload,
        params=params,
    )


def list_entries(incident_id: str, stream_id: str) -> List[Dict[str, Any]]:
    return _client().get(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/entries"
    )


def update_entry(incident_id: str, entry_id: str, data: "EntryUpdate", stream_id: str | None = None) -> Dict[str, Any] | None:
    if not isinstance(data, EntryUpdate):
        data = EntryUpdate(**(data or {}))
    if not stream_id:
        raise ValueError("stream_id is required for update_entry")
    return _client().put(
        f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/entries/{entry_id}",
        json=data.model_dump(exclude_unset=True),
    )


def delete_entry(incident_id: str, entry_id: str, stream_id: str | None = None) -> bool:
    if not stream_id:
        raise ValueError("stream_id is required for delete_entry")
    try:
        _client().delete(
            f"/api/incidents/{incident_id}/ics214/streams/{stream_id}/entries/{entry_id}",
        )
        return True
    except Exception:
        return False


# Event ingestion -------------------------------------------------------------

def ingest_event_to_entries(event: Dict[str, Any]) -> List[Dict[str, Any]]:
    incident_id = event["incident_id"]
    result = _client().post(
        f"/api/incidents/{incident_id}/ics214/ingest-event",
        json=event,
    )
    return result.get("created", [])


# Export ---------------------------------------------------------------------

def export_stream(incident_id: str, stream_id: str, options: ExportRequest):
    """Generate and save a PDF export of the stream.

    This replicates the old SQLAlchemy logic locally: pulls entries from the
    API then calls the forms export utility.  The export record is written
    locally since there is no dedicated export endpoint yet.
    """
    import uuid
    from datetime import datetime, timezone
    from pathlib import Path

    entries = list_entries(incident_id, stream_id)
    if not options.include_auto:
        entries = [e for e in entries if not e.get("autogenerated")]

    base_dir = Path("data") / "uploads" / "ics214" / incident_id
    base_dir.mkdir(parents=True, exist_ok=True)
    filename = f"{stream_id}_{int(datetime.now(timezone.utc).timestamp())}.pdf"
    file_path = base_dir / filename

    from modules.forms_creator.api import export_form_unified
    export_form_unified(
        "ics_214",
        file_path,
        values={"entries": entries},
        context={"incident_id": incident_id},
    )

    class _ExportResult:
        def __init__(self, id_, file_path_, created_at_):
            self.id = id_
            self.file_path = str(file_path_)
            self.created_at = created_at_

    return _ExportResult(
        id_=str(uuid.uuid4()),
        file_path_=file_path,
        created_at_=datetime.now(timezone.utc),
    )
