"""Style system package providing theme palettes and framework adapters."""

from .styles import (
    THEME_NAME,
    StyleBus,
    style_bus,
    get_palette,
    apply_app_palette,
    set_theme,
    subscribe_theme,
    team_status_colors,
    task_status_colors,
    TEAM_TYPE_COLORS,
    intel_subject_status_colors,
    intel_assessment_status_colors,
    intel_item_status_colors,
    intel_lead_status_colors,
    intel_entity_colors,
    intel_priority_colors,
    intel_trend_colors,
)

__all__ = [
    'THEME_NAME',
    'StyleBus',
    'style_bus',
    'get_palette',
    'apply_app_palette',
    'set_theme',
    'subscribe_theme',
    'team_status_colors',
    'task_status_colors',
    'TEAM_TYPE_COLORS',
    'intel_subject_status_colors',
    'intel_assessment_status_colors',
    'intel_item_status_colors',
    'intel_lead_status_colors',
    'intel_entity_colors',
    'intel_priority_colors',
    'intel_trend_colors',
]
