import QtQuick
import QtQuick.Controls

Item {
    id: root
    signal exportRequested(bool includeAuto, bool includeAttachments)
    Column {
        anchors.centerIn: parent
        CheckBox { id: autoBox; text: "Include autogenerated"; checked: true }
        CheckBox { id: attachBox; text: "Include attachments" }
        Button { text: "Export PDF"; onClicked: root.exportRequested(autoBox.checked, attachBox.checked) }
    }
}
